Reward: 300
RewardCooldownHours: 3
Shop:
  Items:
    kokaina:
      name: §eFeinstes Koks
      type: SUGAR
      lore:
        - Erste line
        - Zweite line
      amount: 1
      cost: 200
    fly:
      name: §eFlügels AMK
      type: ELYTRA
      lore:
        - Erste xd
        - Zweite dx
      amount: 1
      cost: 1000
    firework:
      name: §eBooster
      type: FIREWORK_ROCKET
      lore:
        - Erste line
        - Zweite line
      amount: 1
      cost: 1
    fireworkL:
      name: §eBooster
      type: FIREWORK_ROCKET
      lore:
        - Erste line
        - Zweite line
      amount: 64
      cost: 64
