name: PeachForestX
version: '${project.version}'
main: de.davideinenkel.peachforestx.PeachForestX
api-version: 1.19
commands:
  shop:
    description: Hehehe du Huan
  setup:
    description: Menu bekommen kla
