name: PeachForestX
version: '${project.version}'
main: de.davideinenkel.peachforestx.PeachForestX
api-version: 1.19
commands:
  pfreload:
    description: Reload config
  test:
    description: Variable test command
  balance:
    description: Manipulate player balance
  shop:
    description: Hehehe du Huan
  setup:
    description: Menu bekommen kla
  acceptTradeRequest:
  declineTradeRequest: